// Code generated by mockery v2.6.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Graphics is an autogenerated mock type for the Graphics type
type Graphics struct {
	mock.Mock
}

// Clear provides a mock function with given fields:
func (_m *Graphics) Clear() {
	_m.Called()
}

// TogglePixel provides a mock function with given fields: x, y
func (_m *Graphics) TogglePixel(x int, y int) bool {
	ret := _m.Called(x, y)

	var r0 bool
	if rf, ok := ret.Get(0).(func(int, int) bool); ok {
		r0 = rf(x, y)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
